### ISSUE TITLE
Using ChildRow

### ISSUE THREAD

**Issue by mike131** [volosoft/jtable#104]
Hi I am confused on how to add information to child row.

I currently have an image/icon where onclick will allow toggling open/close of the child row.

Can you provide an example of how to add data to the child row for display?

Thank you

**Comment by ralosoft** [comment]
hi, do you know how to hide the new row(some data) with another click or click outside the row?because the row opened keeps showing the data of the row always.

Thanks

**Comment by mike131** [comment]
@ralosoft Take a look at the API Reference.
http://www.jtable.org/ApiReference/Methods#met-closeChildRow

I believe this is what you are looking for. You would need to call the API command on your triggers.

**Comment by ralosoft** [comment]
Thanks mike131, your suggest helped me, i found the next code in a section of this github (hikalkan) 

 width: '1%',
                    sorting: false,
                    edit: false,
                    create: false,
                    display: function (rawMaterialData) {
                        var $img = $('Inci');
                        $img.click(function () {
                            if ($('#RawMaterialsContainer').jtable('isChildRowOpen', $img.closest('tr'))) {
                                $('#RawMaterialsContainer').jtable('closeChildRow', $img.closest('tr'));
                            }
                            else {
                                var $childRow = $('#RawMaterialsContainer').jtable('openChildRow', $img.closest('tr'));
                                $childRow.find('td').addClass('noscroll').html(createInciHtml(rawMaterialData.record.CatalogLabels));
                            }
                        });
                        return $img;
                    }
                }
