### ISSUE TITLE
How to set the maxLength property in a field?

### ISSUE THREAD

**Issue by silvioprog** [volosoft/jtable#1071]
Hello,

I'm trying:

``` jquery
...
    fields: {
        id: {
            key: true,
            list: false
        },
        nome: {
            title: 'Nome',
            width: '70%',
            maxLength: 50,
            inputClass: 'validate[required]'
        },
...
```

But, does not works. Can I set the maxLength via any jTable property or plugin?

Thank you and sorry for my questions!

**Comment by funkodelic** [comment]
Hi, maxSize doesn't work for me, can you tell me how did you fix it?

**Comment by amberdiehl** [comment]
Hi, this didn't work for me either; did this fix it?

**Comment by silvioprog** [comment]
Hello dudes, I just declared [jQuery-Validation-Engine](https://cdnjs.com/libraries/jQuery-Validation-Engine) in the page and set `'validate[required],custom[maxSize[50]]'` to the `inputClass`.
