### ISSUE TITLE
Feature Req: Muli-Column Edit

### ISSUE THREAD

**Issue by LamboJay** [volosoft/jtable#108]
I have a table with a large number of columns. It would be nice to be able to set the number of columns on the edit/add forms to reduce browser scrolling.

Something like this:

```
    $('#tableContainer').jtable({
        title: 'Products',
        paging: true,
        pageSize: 15,
        editColumns: 2,   // Use 2 columns on edit form. Default to 1. 
        sorting: true,
```

Would generate this:
![ColumnEdit](https://f.cloud.github.com/assets/3267980/86711/770ed766-64a8-11e2-9649-340e4196137f.png)
Thanks.

**Comment by shahnamita** [comment]
Hi,

Can I remove text field from Edit form conditionally in jtable?
pls reply me as soon as psbl
