### ISSUE TITLE
Child table icon + toggle open/close SOLLUTION

### ISSUE THREAD

**Issue by vygandas1024** [volosoft/jtable#109]
Since I like the interface to be as intuitive as possible, I added a simple open/close toggle action when user clicks on the child table icon (which is displayed in parent table cell).

``` javascript
//CHILD TABLE ====================================
komentarai: {  //parameters for a parent column
    title: '', //I like to hide the title bar - this gives me a clean look
    width: '1%', //width of the + - icon column
    sorting: false,
    edit: false,
    create: false,
    display: function (data5) { //this is a sample from 5th level child, so I name data accordingly
        var $img5 = $('<img class="plius" src="images/plius.png" title="Child table" />');
        //$img5.click(function () {    - used to be click function, be changed to toggle
        $img5.toggle(function () {  //first part of toggle function goes here
            $(this).attr('src', 'images/minus.png'); //on open child table, change the icon
            $('#jIrodymai').jtable('openChildTable',  //as usual, child table with params
                $img5.closest('tr'),
                {
                title: '"' + data5.record.irod_nr + '" contents:', //example title
                showCloseButton: false, //I hide close button, not to mess with toggle

.....

                }, function (data) { //opened handler
                data.childTable.jtable('load');
            });
        //}); - used to be the end, but we added toggle, so here goes the second part:

        //toggle
        },  function(){  
            $('#jIrodymai').jtable('closeChildTable',$img5.closest('tr'));
            $(this).attr('src', 'images/plius.png'); //change the icon back to "plus"
        }); //TOGGLE


    //Return image to show on the row
    return $img5;
    }
},
```

Anyway, I think the code can be optimised and cleaned up - anyone can contribute :)
Here is my end result:
![pliusminus](https://f.cloud.github.com/assets/3253473/87530/7d0b59dc-64c6-11e2-9dec-822fd28cf233.jpg)

And my icons if you like them:
![minus](https://f.cloud.github.com/assets/3253473/87532/93693f32-64c6-11e2-9728-8cdd3c28acce.png)
![plius](https://f.cloud.github.com/assets/3253473/87533/9a1e7b94-64c6-11e2-8a19-cb82a6da5b3a.png)

Only one minor thing - with master table option to open/close child tables as accordeon - the icon "forgets" to come back to "plus". Maybe anyone has an idea how to fix that?

**Comment by anoob-kd** [comment]
Hi Guy's
I am using two toggle ,
if possible for open/close ?
how can change that script ?

**Comment by peterboccia** [comment]
Yesterday I do it.
You can simply apply a class to the button when you click it and check it at the beginning.
I provide an example:
```
var $img = $('<img src="/Content/images/Misc/phone.png" title="Edit phone numbers" />');
$img.click(function (e) {
	if($(this).hasClass('closeChild')){
		// you should close it
	}
	else {
		$(this).addClass('closeChild');
		// open you child table
	}
}
return $img;
```
Hope this help

**Comment by dannetstudio** [comment]
The previous example works very well, but remember to remove the class "closeChild" after closing the child table because if not it will works only the first time (it will check if the element has the class, and if not it will add it and will not open anymore because the class will be there)

Example: 

$img.click(function (e) {
    if($(this).hasClass('closeChild')){
	$('#' + opt_JTable_ID + '').jtable('closeChildTable',$img.closest('tr'));
       $(this).removeClass('closeChild'); // we remove the class after closing child.
    }
    else {
        $(this).addClass('closeChild');
        // open you child table
    }
}
return $img;
