### ISSUE TITLE
Style not implemented in Add/Edit modal

### ISSUE THREAD

**Issue by mii9000** [volosoft/jtable#1121]
I have included the following files to work with jTable. jTable's style is applied but the modal is not showing the same theme.

```
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Scripts/jtable/themes/metro/blue/jtable.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.10.4.min.js"></script>
<script src="~/Scripts/jtable/jquery.jtable.min.js"></script>
```

Can someone please point out why?

**Comment by missingfaktor** [comment]
I had the same problem and this helped. Thanks @shekharquexst.

**Comment by MYounas** [comment]
Hey @shekharquexst  there is nothing any link or jquery metro ui file on http://jquit.com/builder,Please help,Thanx
