### ISSUE TITLE
Disabling add/edit/delete buttons / custom add/edit buttons 

### ISSUE THREAD

**Issue by gzbucki** [volosoft/jtable#116]
Hi,

Today i had to turn off these buttons for one specific jtable instance and it took me some time to "dig in". I think that giving the option to enable/disable them would be good feature.

Also in other table i needed to stop add/edit buttons from doing default actions and replace it with simple href (for adding/editing data, wich couldn't be displayed properly in jqueryUI dialog)

**Comment by dotjose** [comment]
What about editing the jtable api button markup. Like I need rather than the default edit and delete icon I need my own custom button having glyph-icon and button text.
Example: <button class="jtable-command-button glyphicon glyphicon-pencil btn btn-warning"> Edit </button>

Is that possible?

**Comment by danielabbatt** [comment]
You could use jquery to modify the html content of the button when the form loads.
