### ISSUE TITLE
Add an extra column to display the record in another page. 

### ISSUE THREAD

**Issue by genarocupil** [volosoft/jtable#117]
I need to do something like this:

table with 3 columns edit, delete and display:
![pic1](https://f.cloud.github.com/assets/536089/91601/7af82d7e-65a6-11e2-974d-e546c4fac83f.png)

Image 2:
if click in button display i can get "id" of any row/record:
![pic2](https://f.cloud.github.com/assets/536089/91602/85180a0e-65a6-11e2-99a4-e3ca53668cdf.png)

i dont know what to do that if you can help me thank you.

**Comment by saineshwar** [comment]
Working Example

ContactName: {
                        title: 'ContactName',
                        width: '20%',
                        display: function (data)
                        {
                            if (data.record.ContactName.trim() == "Saineshwar Bageri")
                            {
                                return '<a target="_blank" href="/Demo/DeleteCustomer?CustomerID=' + data.record.CustomerID + '">Edit Users Link</a>';
                            }
                            else {
                                return data.record.ContactName;
                            }
                        }
                    },
