### ISSUE TITLE
listAction Function with Static Data

### ISSUE THREAD

**Issue by JPadster** [volosoft/jtable#1278]
HI,

I'm trying a simple example handing off listAction to a function, not to a server post.

function foo() {
    return {
        "Result": "OK",
        "Records": [{ "Id": 1, "ArchiveId": "39", "ServiceNumber": "123", "SourceNumber": "a", "SalesName": "Sarah", "Type": "1", "UserName": "Me"}],
        "TotalRecordCount": 1
    };
   }

title: 'Deployment History',
            actions: {
                listAction: foo(),
                deleteAction: '@Url.Action("myDelete")',
                updateAction: '@Url.Action("myUpdate")',
                createAction: '@Url.Action("myCreate")'
            },

Nothing is returned and I get a cannot communicate with server error. I didn't think it would be connecting to a server as its static data being returned.

**Comment by mwalker2k12** [comment]
Can somebody post a working example of a jtable using a local static function to return some static data and binding the grid? I can't get it to work for the life of me. I keep getting originalListAction.method(...).done is not a function. If I call a method from the server it works fine, but not using a local js function.

**Comment by hsharma89** [comment]
Hi,
 I am facing same problem. Any update on this?

Thanks

**Comment by dasguptahirak** [comment]
@hsharma89 
Have you followed this ?

![Screenshot_2019-11-20-00-09-33-80](https://user-images.githubusercontent.com/7932509/69175685-37bebb00-0b2a-11ea-86fb-96e2dcd2dc90.png)

**Comment by hsharma89** [comment]
yes, i did. but its not working.
