### ISSUE TITLE
Dynamically changing title (and other options)

### ISSUE THREAD

**Issue by stoshb** [volosoft/jtable#1294]
I am loading a jtable based upon data created in earlier steps by using:

$('#ProjectContainer').jtable({
    title: 'ProjectTitle',
        .
       etc
       .
}

function ClickButton( Co_Record )
{
    $('#ProjectContainer').jtable( "load", 
        {CO_ID: Co_Record.CO_ID} , 
        ProjLoadedCB(Co_Record));
}

I want to make sure that the title of the loaded table contains a the field Co_Record.CO_NAME.  

Want to do something simple like:

$('#ProjectContaine').title = Co_Record.CO_NAME

in either of the functions ClickButton or ProjLoadedCB.

I know the syntax shown doesn't work but it expresses the function I want.

Thanks for any help.

**Comment by anoob-kd** [comment]
how can create dynamically change grouping in jtable

**Comment by saravanakumarv** [comment]
how to create dynamic fields or how to create dynamic headers.if user enter text into the textbox and click the button the entered text will be header of the table.
