### ISSUE TITLE
Responsive Design *feature

### ISSUE THREAD

**Issue by alxmau** [volosoft/jtable#134]
Just wondering what the best way to implement a responsive design using jtable

**Comment by solartom** [comment]
It would be great to have something similar to this https://css-tricks.com/examples/ResponsiveTables/responsive.php

**Comment by saimadhan** [comment]
Hi
is it possible to make Jtable  responsive design

**Comment by gigeCDN** [comment]
I would pay for a responsive commercial version, kick start it :)
