### ISSUE TITLE
jTbale 2.4.0 Not able view in IE 8.0

### ISSUE THREAD

**Issue by MathavanN** [volosoft/jtable#1351]
Hi, 
I am using jTbale 2.4.0 in asp.net web application. but i am not able to view the jtbale in IE 8.0, but it is showing in chrome, firefox..
jQuery version 2.1.1
jQuery UI - v1.10.4
please help me to fix this issue.

Thanks.

**Comment by sandeepmeenuga** [comment]
In Chrome data loading of 500 records is taking consistently 4 or 5 seconds, but same count of records loading in IE 10 or 11 taking almost 20 seconds. Can you guide me how to reduce the amount of time in IE 10 or 11.
