### ISSUE TITLE
Set checkbox field value from Database.

### ISSUE THREAD

**Issue by ghost** [volosoft/jtable#1363]
I am new in this and i need help with setting checkbox value, which i get from database. I do not mean selecting checbox, but setting boolean value. I can only set default value, which i dont want to set. I am using PHP if its relevant. If it would be possible i would like to show checkbox instead of its value. Thanks

**Comment by tchoulihan** [comment]
This helped me out a lot, thanks!

I'd also like to add that my values also needed to be changed to:
```javascript
values: {
   false: '',
   true: ''
},
```

And the column for that was a Mysql TINYINT(1)
