### ISSUE TITLE
Replace AJAX by sockets (Node.js, socket.io)

### ISSUE THREAD

**Issue by tibotiber** [volosoft/jtable#1465]
Hi! 
Love your work on JTable, it is from far the best CRUD jQuery table lib around :+1: 
What would make it even better though is the ability to switch from AJAX to sockets for the communication. Socket.io comes very often in Node.js apps nowadays so it may be interesting for a lot of people. Plus that would be much more efficient since the client-server communication would stay open with your web page.

So a few questions:
- any work that has been done on that previously?
- any chance it would be supported in the future?
- how difficult would it be to implement?
- anyone wanting to collaborate on a pull request for this?

Thanks!

**Comment by Pouet4205** [comment]
Hi, I'm interested in jTable and socket.io, what's up on this subject ?

**Comment by tibotiber** [comment]
@Pouet4205 I'm not maintaining the project I used jtable on anymore, but you can see the diff of the commit where I swapped ajax for socket.io at https://github.com/tibotiber/greeny-oms/commit/f3f73d5369a9e23dedf7de3e83b412b1e2d3c1df. I think it's pretty clean and straightforward, although you have to modify the jtable source. Hopefully you agree with that :). I don't mind pushing a PR if maintainers are interested and have some advice on how they envision changes to be organised. One more thing, you can use csrf tokens as well by adding this at line 1234 of the diff:
```js
// add csrf if available
if(_csrf) {
  if(!options.data) options.data = {};
  options.data._csrf = _csrf;
}
```
