### ISSUE TITLE
Custom Column: Input type file not being posted

### ISSUE THREAD

**Issue by mii9000** [volosoft/jtable#1494]
I have created a custom column in jTable for add form:

``` javascript
UploadImage: {
    title: 'Upload Image',
    list:false,
    input: function (data) {
        return '<input type="file" name="UploadImage" id="Edit-UploadImage" />';
    }
}
```

But when the request is sent it is not including the image file. Why is that and any workarounds?

**Comment by funkodelic** [comment]
Hi, can you show me how you do that, please? i have the same problem.
