### ISSUE TITLE
Totals Row

### ISSUE THREAD

**Issue by criticc** [volosoft/jtable#169]
Hey i think that this isnt implemented yet but is there any way to do a custom row at the end of the jtable with some totals calculated by me?

**Comment by amberdiehl** [comment]
Having landed on this page and seeing there is no sample example using just jQuery, here's what I did. As you an see in the code, I'm just providing a count of records shown and a total. Pretty basic, but hope it helps someone.

<            
            recordsLoaded: function (event, data){
                var footer = $('table.jtable').find('tfoot');
                if (!footer.length) {
                    footer = $('<tfoot>').appendTo('table.jtable');
                    footer.append($('<td id="count">00</td><td id="sum" colspan="6">0.00</td>'));
                }
                var count = 0;
                var total = 0;
                var items = data.serverResponse['Records'];
                $.each(items, function(index, value){
                    count += 1;
                    total += parseFloat(value.amount);
                });
                $('#count').html(count);
                $('#sum').html('$' + total);
            }
>
