### ISSUE TITLE
JQUERY 2.1.1 PROBLEM

### ISSUE THREAD

**Issue by karamizrak** [volosoft/jtable#1868]
Jtable plugin is not work with jquery 2.1.1 version.
Do you know this problem?
$.widget('hik.jtable' , function(....
Widget is not define.

**Comment by hikalkan** [comment]
Hi,

Have you added jQueryUI to your page?

**Comment by karamizrak** [comment]
Yes I Have.
I use ace master bootstrap template. ( http://responsiweb.com/themes/preview/ace/1.3.5/ ).
I solved the problem in another way. I use jqgrid.
