### ISSUE TITLE
New Feature: Toolbar

### ISSUE THREAD

**Issue by hikalkan** [volosoft/jtable#188]
I'm trying to add a toolbar that can be used to add custom icons/buttons to the table. Also, 'add new record' is moved to this toolbar. Does it look good? See image below:

![jtable-toolbar](https://f.cloud.github.com/assets/1210527/124783/e9a498d8-6efd-11e2-9e74-aa6368d9b664.png)

**Comment by carloxy** [comment]
hikalkan, I need put button excel exactly how you did, but I didn't  get.
I know that do very time, but You can help me ?
