### ISSUE TITLE
jQuery datepicker change month & change year functionality is not working inside a jTable type date

### ISSUE THREAD

**Issue by manishbupadhyay** [volosoft/jtable#1908]
I am using jQuery datepicker inside a jTable type date property. when i am adding datepicker property changeMonth: true and changeYear: true inside a jTable then it's not showing dropdown list of month and year date in datepicker. overall it's working the problem is only inside a jtable.
please solve this issue as soon as possible. @hikalkan

**Comment by Monchit** [comment]
formCreated: function (event, data) {
    $(".hasDatepicker").datepicker("option", "changeYear", true);
}
