### ISSUE TITLE
Problems with quotes in text field

### ISSUE THREAD

**Issue by maystr-i** [volosoft/jtable#209]
If i add something like "Hello" in quotes, this word is not visible in Edit form 
![Problem](https://f.cloud.github.com/assets/3515483/141381/00c3204c-7247-11e2-8e43-e123bcffeac4.jpg)

**Comment by RiffsRocks** [comment]
Hi, i see that the problem should be fixed, but, i've actually suffering the same problem. When i ADD or UPDATE a record using "quotes" it doesn't save the changes.
