### ISSUE TITLE
How to change the sorting of a jTable programmatically.

### ISSUE THREAD

**Issue by SirBisgaard** [volosoft/jtable#2091]
Hi there,
-

**(short)** I simply want to be able to know when the sorting is changed and then update the URL, with that specific sorting.

I have a jTable presenting some data, in my angular 2 application. I have to add the sorting of the jTable in the URL. So I'm able to load the page with the data sorted in a specific way. 

> Link example: /data?sorting=Name&20ASC

This is so I can use the angular router to easily navigate back to a specific sort.

> /data => /data?sorting=Something&20ASC => /data/23 => /data?sorting=Name&20ASC

I hope the above makes sense. But it's representing the routing history, and the desired result.

I have tried to read the documentation without any luck, and google cannot find anything either... :(
So how can I implement this kind of functionality into my angular application?

**Comment by dasguptahirak** [comment]
In the server side, you have to handle this string data member for sorting:

jtSorting: A string which represents requested sorting. It is built from sorting field name plus sorting direction. For instance, It can be 'Name ASC', 'BirtDate DESC', 'Age ASC'... etc.

**Comment by SirBisgaard** [comment]
Your answer did not exactly help, but i will use the listAction event.
But thanks for the quick reply. 👍

**Comment by Gonlos** [comment]
Meybe, do you need history.pushState()?
