### ISSUE TITLE
How can I select last page of pagination?

### ISSUE THREAD

**Issue by W3bDan** [volosoft/jtable#2109]
Hi!
How can I select last page of pagination when jtable loaded?
May be does it have configuration for this?

**Comment by sheryever** [comment]
@W3bDan 

Select you jtable container and search for the `.jtable-page-number-last` and call click function.

```javascript
   // call after jtable data loaded.
   $('#YourJtableContainer .jtable-page-number-last').click()
```
**Recommendation** If you have to show the last created records as your first view, then use `defaultSorting' option and set your `entryDate` or `createdOn` table column 'order by desc' instead.
