### ISSUE TITLE
Jtable with a large amount of records

### ISSUE THREAD

**Issue by Aldegonde** [volosoft/jtable#213]
Hi,

When I try to use jtabel with a large amount of records, it get really slow because it needs to have all records in an array:

```
//Add all records to an array
$rows = array();
while($row = mysql_fetch_array($result))
{
    $rows[] = $row;
}
//Return result to jTable
$jTableResult = array();
$jTableResult['Result'] = "OK";
$jTableResult['Records'] = $rows;
```

Can this be changed in a way so it stays quick?

Thanks, and keep up the good work!

**Comment by SanaWaseem** [comment]
What if pagination is not a requirement?
