### ISSUE TITLE
Make Only Some Records Editable?

### ISSUE THREAD

**Issue by guymac** [volosoft/jtable#2210]
Is it possible to define a function or field that controls whether or not a given record/row is editable/deletable? For example, say the table is created in a JSP page that writes in ownerUID = 123, and we only want rows with a matching ownerUID to be editable? [Or, rather, make the user cognizant that only their own records are editable]. Thanks, looks like a really great component.

**Comment by dasguptahirak** [comment]
@guymac 
You can use rowInserted method of jtable which gets called for each and every row during table listing and then check for the value of data.record.ownerUID. If its value is 123 then you can show the edit button otherwise hide the button. Here is the code for that:
```

                         rowInserted: function (event, data) 
			 {
				if(data.record.ownerUID != 123)
					{
					
					data.row.find('.jtable-edit-command-button').css("opacity", 1);
					data.row.find('.jtable-edit-command-button').off("click");
					
					
					
					}
				else
					{
					data.row.find('.jtable-edit-command-button').show();
					data.row.find('.jtable-delete-command-button').show();
					}
				
				},
```

**Comment by guymac** [comment]
Oh, that's perfect, thank you @dasguptahirak .

> @guymac
> You can use rowInserted method of jtable which gets called for each and every row during table listing and then check for the value of data.record.ownerUID. If its value is 123 then you can show the edit button otherwise hide the button. Here is the code for that:
