### ISSUE TITLE
jtable sorting keeps sorted by key

### ISSUE THREAD

**Issue by simple-chu** [volosoft/jtable#2237]
I examined that server side returns record data in a correct order sorted by other column but jtable keeps showing the sorted by key in ascending order.

It seems that when it receives data from jquery, the data set is sorted by key.

**Comment by dasguptahirak** [comment]
@simple-chu 
I think you may have defined **defaultSorting** with your id field in jtable definition like this:

```
$('#StudentTableContainer').jtable({
            title: 'The Student List',
            paging: true, //Enable paging
            pageSize: 10, //Set page size (default: 10)
            sorting: true, //Enable sorting
            defaultSorting: 'studentId ASC', //Set default sorting
            actions: {
                listAction: '/Demo/StudentList',
                deleteAction: '/Demo/DeleteStudent',
                updateAction: '/Demo/UpdateStudent',
                createAction: '/Demo/CreateStudent'
            },
```

**Comment by simple-chu** [comment]
@dasguptahirak 
Thanks for your reply. I have tried :
![Clipboard01](https://user-images.githubusercontent.com/63737292/79433294-813f0380-7fff-11ea-97f0-b94881e05114.jpg)
![Clipboard01](https://user-images.githubusercontent.com/63737292/79433336-8c922f00-7fff-11ea-9c49-0c40d5bcdada.jpg)
![Clipboard01](https://user-images.githubusercontent.com/63737292/79433370-99af1e00-7fff-11ea-85dc-7384040e1469.jpg)



1) remove the defaultSorting,
2) set the defaultSorting to other field DESC
However, I do not set pageSize and paging because I don't use paging.
Is that the problem because of not using paging ?

**Comment by dasguptahirak** [comment]
@simple-chu 
I think you have missed the order(ASC/DESC) in defaultSorting
defaultSorting: 'category ASC'

**Comment by simple-chu** [comment]
@dasguptahirak 
You are so nice ! Thanks again to look at my problem.
In the server side, I do the proper work to get the data in ascending or descending order.
I examine the data to echo.
Then, in the front end, I also check about the response and the data received from response is correct and matches with the server side generated.
However, the data appears on the table is still sorted in ascending order of id !
No matter whether I have set the defaultSorting : 'category DESC' or 'status DESC', it is still sorted in ascending order of id !
![Clipboard01](https://user-images.githubusercontent.com/63737292/79579226-e70fb600-80f9-11ea-88b7-6c9af24e27df.jpg)
![Clipboard02](https://user-images.githubusercontent.com/63737292/79579253-ee36c400-80f9-11ea-8e02-c674e4387170.jpg)
You can see in the responseText, the first record id is 45 but the table still lists out from id 1 !

My setting is 
paging: false,
sorting: true,
fields: {
....
}

**Comment by dasguptahirak** [comment]
@simple-chu 
Have you handled 'jtSorting' variable in server side? 
For sorting you have to fetch the value of jtSorting variable in server side. Even at the time of first listing of jtable, you can see in developer tool that listAction url is being called with jtSorting as request parameter. You have to fetch the value of that variable in server side and pass accordingly to your listing sql query. 

listAction url will be like this if sorting is true:
https://<URL>/listStudentAction?**jtSorting=firstName%20ASC**

**Comment by simple-chu** [comment]
@dasguptahirak 
Yes, I have handled the jtSorting variable and fetch data according to the jtSorting field and ASC or DESC.
I can load the data correctly according to the jtSorting order specified. 
I can also see the data correctly encoded in json in the responseText of client browser, see below.
![Clipboard01](https://user-images.githubusercontent.com/63737292/79639111-1b4bab00-81bc-11ea-869b-ebddef0dc708.jpg)
However, when I look at the preview, they are all arranged in ascending order of id in the console.
![Clipboard02](https://user-images.githubusercontent.com/63737292/79639154-61a10a00-81bc-11ea-9cbf-c45b97501bd4.jpg)
And it shows up arranged in ascending order of key no matter what column header I clicked in ascending or descending order.

**Comment by dasguptahirak** [comment]
Are you doing anything in loadingRecords(event, data) event which s overridding the default sorting? 
Can you share your complete code or reproduce same in jsfiddle? 
Are you facing this problem in all your web pages containing jtable?

**Comment by dasguptahirak** [comment]
@simple-chu 

I understood the root cause of your problem. You are returning 'records' as javascript object not javascript array. 

_An object is an unordered collection of zero or more name/value pairs, where a name is a string and a value is a string, number, boolean, null, object, or array.

An array is an ordered sequence of zero or more values._

Try to return 'records' as javascript object array (records value in square brackets [{}]) like this:

![image](https://user-images.githubusercontent.com/7932509/79774104-fc7e1d80-834f-11ea-9534-2610f51d5e84.png)

**Comment by simple-chu** [comment]
@dasguptahirak 
Oh ! Yes, absolutely ! Thank you so much !!!
Following your answer, I solve it !
Thanks again !
