### ISSUE TITLE
No funciona paginar resultados

### ISSUE THREAD

**Issue by cogare84** [volosoft/jtable#2270]
Hola.
Estoy intentando paginar los resultados con jTable (PHP 8 y MYSQL) y en el pié de la tabla si aparece fraccionado y correcto , segun registros existentes y valores  indicados en la instancia jTable, pero me muestra todos los resultados, enlugar  de los  que indica  la paginación. Os muestro el código por si alguien puede echarme una mano.

INSTANCIA JTABLE
![image](https://user-images.githubusercontent.com/100587335/156146689-d9456864-b9b0-4be7-ad0b-2909187cb968.png)

RESULTADO
![image](https://user-images.githubusercontent.com/100587335/156147259-ca5cd692-ecb3-4421-a897-f83fd9a53053.png)

Gracias de antemano y un saludo.

**Comment by misterparsons** [comment]
This is the same problem as issue #2259

**Comment by cogare84** [comment]
Perfecto, si. Solucionado.

Gracias por la ayuda!!!!
