### ISSUE TITLE
Posibility to limit the row height,

### ISSUE THREAD

**Issue by arnold-b** [volosoft/jtable#2281]
Hi and thanks. 
Is there any way to limit the row height. that it showes only the first or the first 2 lines instead of the whole entry 
Thanks

**Comment by misterparsons** [comment]
Hi,

You can use the listClass property to make jTable give the troublesome cells a class, and standard css (max-height and overflow) to control the appearance of the cell.

**Comment by arnold-b** [comment]
Thanks to this very active group. 
I solved it like that:

comment: {
                    title: 'Comment',
					listClass:"itemListcomment",
		    type: 'textarea',
                    list: true,
		    layoutBreak: false

                },
                
                CSS: 
                .itemListcomment {
 overflow: hidden;
  display: -webkit-box;
  /* display 2 lines only */
  -webkit-line-clamp: 4;
  line-clamp: 4;
  -webkit-box-orient: vertical;
 
}
