### ISSUE TITLE
Switching visibilty of a column

### ISSUE THREAD

**Issue by enterpub** [volosoft/jtable#25]
Hi, is there a way to hide or show some column by condition?
I have a search form. If user fills in specific text box and clicks submit I need to show additional column. If then he clears that text box and clicks submit again I need to hide the column.
I have tried to dynamically set "list" property to 'true' or 'false' - it remembers the first time setting and does not change after.
Thank you for reply

**Comment by dyoji** [comment]
@enterpub , do this:
      value1: {
        title: 'something',
        width: '20%',
        list: (function() {
          if(condition met) {
             return true;
          } else { 
             return false;
        })(),
      },

**Comment by pradippatel1411** [comment]
$('#JtableGridId').jtable('changeColumnVisibility', 'ColumnName', 'visible');

$('#JtableGridId').jtable('changeColumnVisibility', 'ColumnName','hidden');
