### ISSUE TITLE
Problem when press enter key in "Create Dialog Form"

### ISSUE THREAD

**Issue by MrMichetti** [volosoft/jtable#254]
Hi,
I have a problem when i press Enter Key to send the request in Create Dialog form.
If i press the button with mouse all work ok, but if i press enter the ajax call doesn't work and jtable redirect to the ajax url request.
Someone have the same problem and help me?

Now i had disabled the enter key in the form with js :(

**Comment by nonozor** [comment]
Great tahks michalzalewski : you've saved my day !
