### ISSUE TITLE
displayFormat won't work, showing 'NaN.NaN.NaN'

### ISSUE THREAD

**Issue by softshape** [volosoft/jtable#400]
Hi,

I have a date field in the table -

```
validUntil: {
    title: 'Valid until',
    type: 'date',
    displayFormat: 'dd.mm.yy'
},
```

The date format is changed to 'dd.mm.yy'. 

When validUntil comes from a server, it's correct: "validUntil": "18.03.2013"
But on the page itself I see 'NaN.NaN.NaN' instead on the date.

Please help!

**Comment by te0z** [comment]
Hi,

The problem maybe is in SQL query, because if you use SELECT DATE FROM XXXX, will return a value type date, try to do this...
SELECT CONVERT(VARCHAR(11),DATE,103) AS DATE
this return a value compatible, 

probe.
