### ISSUE TITLE
IE specific fix for dropdown redraw.

### ISSUE THREAD

**Issue by TroyWitthoeft** [volosoft/jtable#527]
Not a jTable bug, but help for others using dropdown tables and IE (have mercy on us)

I was having an IE specific issue where my dropdown boxes would not draw correctly on screen. Everything worked fine in Chrome and all the HTML was correct.  Opening developer tools (F12) in IE verfied this.  It simply would not display onscreen! Furthermore, pressing the up and down arrow keys would allow you to cycle through and select the expected options, they just weren't in the expanded list!  Very strange.  Thank you MS.  

The fix for me was to add a single line to jtable.js which forces a redraw on the _fillDropDownListWithOptions method.  Hope it helps someone! 

<pre>        /* Fills a dropdown list with given options.
        *************************************************************************/
        _fillDropDownListWithOptions: function ($select, options, value) {
            $select.empty();
            for (var i = 0; i < options.length; i++) {
                $('<option' + (options[i].Value == value ? ' selected="selected"' : '') + '>' + options[i].DisplayText + '</option>')
                    .val(options[i].Value)
                    .appendTo($select);
            }
            //IE Hack to redraw dropdown box.   
            $select.hide().show();
        },</pre>

Someone could probably improve the above by adding an "If IE" detection around the hack, but it works for me. 

These articles [<a href="http://stackoverflow.com/questions/1637503/jquery-change-event-on-select-not-firing-in-ie">1</a>][<a href="http://www.quirksmode.org/dom/events/change.html#t05">2</a>] lead me to believe that the .change function used in _makeCascadeDropDowns may be the culprit, however changing it to .click did nothing.  Only a forced redraw worked for me.

**Comment by sandeepmeenuga** [comment]
In Chrome data loading of 500 records is taking consistently 4 or 5 seconds, but same count of records loading in IE 10 or 11 taking almost 20 seconds. Can you guide me how to reduce the amount of time in IE 10 or 11.
