### ISSUE TITLE
Cache when loading Options from URL

### ISSUE THREAD

**Issue by gbisheimer** [volosoft/jtable#63]
Hi hikalkan,

It would be nice to have the posibility to clear cache contents on demand, or may be, just not store data retrieved from database into the cache, as it may be constantly changing and cache prevents showing new data.

Thank you. Cheers!,

gbisheimer

**Comment by shahrpt** [comment]
Hi Everyone,
I has been a while, but I am facing the same issue "Foksadure" is facing. I am loading multiple option in  a jtable I am using and it is a performance overhead now. Can you please direct me to a better solution  here? A solution like where I can load all the options at once and then reuse the json objects for different options. 

Best Regards,
Sulman

**Comment by Foksadure** [comment]
@shahrpt (Sulman) :+1: 

Hi,

FYI, in my case, I ended up using [mockjax](https://github.com/jakerella/jquery-mockjax) to prefetch and cache datas locally, which then fools jtable Ajax calls for these datas.
Works like a charm : performance problem solved.
Then again, these are static values (zipcodes, basically).

Cheers.
