### ISSUE TITLE
Jtable conflict with popup of ckeditor

### ISSUE THREAD

**Issue by golden-illusion** [volosoft/jtable#829]
![jatble](https://f.cloud.github.com/assets/1073646/943560/c7e40508-022d-11e3-92d1-170196cafedf.jpg)

Hi! I use Jtable for few months and recently integrate with ckeditor. I got data back from ckeditor to jtable well, however when i open a popup (ex: youtube), the input field go to input form of Jtable instead of the popup!

How could i solve it? thanks!

**Comment by wahisoufiane** [comment]
I have the same problem, and I put the jqueryui 1.11.4 but still have the same problem, @golden-illusion : can you please guide me to the solution you found.
