### ISSUE TITLE
acentos y caracteres especiales (accents and letter ' ñ ' )

### ISSUE THREAD

**Issue by hbernal** [volosoft/jtable#839]
Español
Cuando listas campos que tienen información que contienen acentos ó la 'ñ', el valor del campo se muestra en blanco, alguien ha solucionado este detalle?

When list fields with data in spanish like accent or letter 'ñ', when the data is listing only show empty spaces, someone has fixed this detail?

thanks in advanced

**Comment by omarcresp** [comment]
pero a mi me sucede esto trabajando en local con el cmd
