### ISSUE TITLE
Add record dialog doesn't close even when AJAX response is "OK".

### ISSUE THREAD

**Issue by Harmonitron** [volosoft/jtable#872]
Browser: Firefox 20.

I'm new to jTable and adapting the Getting Started page for my requirements. I have 'Creating the list action' working properly.

I have moved on to the 'Creating a new record' section. When I click 'Add new record', fill in the form and hit 'Save' the data is posted to the DB and successfully inserted. The following data is returned to the browser (and verified with Firebug).

{"Result":"OK","Records":[{"System_ID":"169","Location":"Attic","SystemName":"Server","DeviceName":"Ubuntu","Access_Level":"root","Login":"root","Password":"passw","Active":"1","Notes":"Notes go here."}]}

The data table is updated correctly but the dialog never closes.

Any ideas?

**Comment by ejlmljt** [comment]
I have a problem in a similar vein but my jtable web page seems to fall through and execute all actions.
When I call the web page it lists the records for the listactions listAction but then gives a 502 error message for the createAction script even though I have clicked on the "+" icon to create a record.
When I click "+" plus I can create a record and receive it at the server. How do I get rid of the 502.
I have compared my script to the php demo one and don't think I have missed anything but you never know. 
Html:
<div id="AccessionTableContainer" style="width: 600px;"></div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#AccessionTableContainer').jtable({
            title: 'Table of accession',
            actions: {
                listAction: 'http://localhost//PythonCgi/sqlServer_pim.py',
                createAction: 'http://localhost/PythonCgi/create_recordPIM.py',
                updateAction: '',
                deleteAction: ''
            },
            fields: {
                ID: {
                	title: 'Id',
                    list: true,
					 key: true,
					 list: true,
                     width: '5%'
                },
                UNIQUENAME: {
                    title: 'Unique name',
                    width: '5%'
                }
                /* ,
                SHORTDESC: {
                    title: 'Short desc.',
                    width: '3%'
                },
                LONGDESC: {
					title: 'Long desc.',
					width: '5%'
                },
                COMMENTS:
                 {
					title: 'Comments',
					width: '5%'
                },
                ENTRYDATE: {
                    title: 'entry date',
                    width: '3%',
                     type: 'date',
                    create: true,
                    edit: true,
                },
                ITEM_TYPE_ID: {
					title: 'Item type id',
					width: '1%'
                },
                UNIQUE_ABBR :
                {
					title: 'Unique Abbrv.',
					width: '3%'
			    },
				CHILD_ID :
				{
					title: 'Child id.',
					width: '1%'
							    },
				DUPLICATE_UNIQUENAMES :
				{
             		title: 'Duplicate id',
					width: '1%'
							    },
				REVISED_UNIQUENAME : {
								title: 'Revised id',
								width: '1%'
							    },
		 		PARENT_ID : {
		 			title: 'Parent id',
							width: '1%'
			    },
			    ID_NO : {
					title: 'Numeric id',
					width: '3%',
               } */
            }
        });
        //Load Accession list from server
	 $('#AccessionTableContainer').jtable('load');
    });
</script>
Python 

response = {
    "Result":"OK",
    "Record":[ 
               {"ID": "aa1",  "UNIQUENAME": "bb", "SHORTDESC": "cc", "LONGDESC": "dd","COMMENTS": "ee", "ENTRYDATE": "/Date(1421884800)/", "ITEM_TYPE_ID": 1, "UNIQUE_ABBR" : "ff", "CHILD_ID" : 2 , "DUPLICATE_UNIQUENAMES" : 3 , "REVISED_UNIQUENAME" : 4,       "PARENT_ID" : 5 ,  "ID_NO" : 6 }
              ]
   }

jsonResponse = json.JSONEncoder().encode(response)

try:
    jsonTest = json.loads(jsonResponse)
#        print ("json test passed\n")
except:
    print ("json test failed\n")

chrome error message
create_recordPIM.py
/PythonCgi
POST	502
Bad Gateway
text/html	jquery.min.js:4
Script
5.6 KB
5.4 KB
440 ms
440 ms


print ("Content-type: application/json" )
print ()
print (jsonResponse)
Platform:Windows 7
web server: iis 
language : python
