### ISSUE TITLE
Programmatically UnSelect Selected Rows

### ISSUE THREAD

**Issue by knoxv1lle** [volosoft/jtable#894]
Is there a way to unselect (clear) the user selected rows in JTable?

**Comment by sevencardz** [comment]
You can extend jtable (v2.4.0) and expose the internal deselectRows function:
```javascript
$.extend(true, $.hik.jtable.prototype, {
	deselectRows: function($rows) {
		this._deselectRows($rows);
		this._onSelectionChanged();
	}
});
```
Then you can call it like you would call selectRows:
```javascript
$myJtable.jtable('deselectRows', $rows);
```

**Comment by PreshitDesai** [comment]
Another working solution:
**$('.jtable-column-header-selecting input').trigger('click');**
