### ISSUE TITLE
Reference child table records

### ISSUE THREAD

**Issue by Mal-function** [volosoft/jtable#937]
I have managed to create a custom button on a standard jtable and passed the ID of the row by using data.record.styleid

I am now creating a custom button on a child table and need to pass the ID of the child row, but i am not having any luck in finding the correct syntax to reference the records of the child table.

Any assistance would be most helpful, thanks.

**Comment by te0z** [comment]
I have the same problem, i cant get the ID from childtable.... any help?

**Comment by Mal-function** [comment]
This project was some time ago but I can share the final code that worked. 
There were a lot of dynamic page changes since the code you saw from Oct 2013, as well as the use of a custom edit modal.
...
	$(document).ready(function () {         
		$('#style_set_table').jtable({
			jqueryuiTheme: true, 				
			title: '<?php echo $page; ?>',            
			paging: false, //Enable paging            
			sorting: false, //Enable sorting       
			openChildAsAccordion: true,
			actions: {                
				listAction:   '<?php echo "http://".$svr."/".$app."/actions/".$filename_with_ext."?action=list" ;?>',
				deleteAction: '<?php echo "http://".$svr."/".$app."/actions/".$filename_with_ext."?action=delete" ;?>',
				updateAction: '<?php echo "http://".$svr."/".$app."/actions/".$filename_with_ext."?action=update" ;?>',
				createAction: '<?php echo "http://".$svr."/".$app."/actions/".$filename_with_ext."?action=create" ;?>'
			},            
			fields: {
				Properties: {
					title: '',
					width: '10%',
					sorting: false,
					edit: false,
					create: false,
					display: function (data) {
						//Create an image that will be used to open child table
						var $img = $('<img src="images/list-grey.png" style="cursor:pointer;" title="Properties" />');
						//Open child table when user clicks the image                        
						$img.click(function () {
							$('#style_set_table').jtable('openChildTable',
								$img.closest('tr'), //Parent row
								{
								title: 'Properties',
								actions: {                
								listAction:   '<?php echo "http://".$svr."/".$app."/actions/".$filename_with_ext."?action=childlist?StyleSetID=" ;?>' + data.record.StyleSetID
								},
								fields: {
									StyleSetPropertyID: {
										key: true,
										create: false,
										edit: false,
										list: true,
										width: '10%',
										display: function(data) {
										return '<img src="js/jtable.2.3.0/themes/jqueryui/edit.png" style="cursor:pointer;" title="Edit Property" onclick="openEdit(' + data.record.StyleSetPropertyID + ',\'' + data.record.StyleSetPropertyValue + '\',\'' + data.record.PropertyTypeEditor + '\',\'' + data.record.PropertyValueOptions + '\');"/>';
										}
									},
									StyleSetID: {
										create: false,
										edit: false,
										list: false
									},
									PropertyID: {
										title: 'Property',
										width: '40%',
										options: <?php echo $PropertyNameOptions; ?>
									},
									StyleSetPropertyValue: {
										create: false,
										edit: false,
										list: true,
										title: 'Value',
										width: '40%'
									},
									PropertyTypeEditor: {
										create: false,
										edit: false,
										list: false
									},
									PropertyValueOptions: {
										create: false,
										edit: false,
										list: false
									}
								}
							}, function (data) { //opened handler
								data.childTable.jtable('load');
							});
							});
					
						//Return image to show on the person row
						return $img;
					}
				},
				StyleSetID: {
					key: true,
					create: false,
					edit: false,
					list: false
				},
				StyleID: {
					title: 'Name',
					width: '45%',
					options: <?php echo $StyleNameOptions; ?>
				},
				PropertySubCategoryID: {
					title: 'Type',
					width: '45%',
					options: <?php echo $PropertySubCategoryNameOptions; ?>
				}
				
			}        
		
	});         
		
		//Load list from server     
		$('#style_set_table').jtable('load');    
	}); 
...
